-- Import subscribers from CSV file
-- All subscribers are added as active without confirmation emails

INSERT INTO newsletter_subscribers (email, name, is_active, confirmed_at, confirmation_token)
VALUES
  ('adina-luminita@hotmail.com', NULL, true, now(), NULL),
  ('ahlbergmum@gmail.com', 'Helene Ahlberg', true, now(), NULL),
  ('ancilundstrom@hotmail.com', 'Anci Lundström', true, now(), NULL),
  ('ancolijo@telia.com', NULL, true, now(), NULL),
  ('andrea.vonrotz@gmail.com', NULL, true, now(), NULL),
  ('anettejohansson75@hotmail.com', NULL, true, now(), NULL),
  ('angelica.foksrod@gmail.com', NULL, true, now(), NULL),
  ('anita_fritzjohansson@yahoo.se', NULL, true, now(), NULL),
  ('ann@gacek.se', 'Ann Gacek', true, now(), NULL),
  ('annahagelin@icloud.com', NULL, true, now(), NULL),
  ('annbrittlundin57@gmail.com', NULL, true, now(), NULL),
  ('annehome@hotmail.com', NULL, true, now(), NULL),
  ('anneli1962marklund@gmail.com', NULL, true, now(), NULL),
  ('annett.nilsson@outlook.com', NULL, true, now(), NULL),
  ('annica.bjoruth@outlook.com', NULL, true, now(), NULL),
  ('annika@forsheda.net', 'Annika Åhsberg', true, now(), NULL),
  ('annikaholm34@gmail.com', NULL, true, now(), NULL),
  ('annmariejonsson@icloud.com', 'Ann-Marie Jonsson', true, now(), NULL),
  ('ave_nossral@hotmail.com', 'Eva Larsson', true, now(), NULL),
  ('bjorkhelen64@gmail.com', NULL, true, now(), NULL),
  ('bo.andren63@gmail.com', 'Bo Andrén', true, now(), NULL),
  ('brittmarie.broman@svenskakyrkan.se', NULL, true, now(), NULL),
  ('carem64@outlook.com', 'Carita Remahl', true, now(), NULL),
  ('cariannerojeras@hotmail.com', 'Carianne Röjerås', true, now(), NULL),
  ('ceu.eriksson@gmail.com', 'Cecilia Stigh', true, now(), NULL),
  ('christina.seldevall@oktv.se', NULL, true, now(), NULL),
  ('cissi@friedmann.se', 'Cecilia Friedmann Niva', true, now(), NULL),
  ('diana@dianaosteopat.se', 'Diana Karlsson', true, now(), NULL),
  ('elinnyg@gmail.com', 'Elin Nygård', true, now(), NULL),
  ('elizalj@bjarenet.com', NULL, true, now(), NULL),
  ('elsa.laurell@live.se', 'Elsa Laurell', true, now(), NULL),
  ('emelie-ekholm1@hotmail.com', 'Emelie Ekholm', true, now(), NULL),
  ('erica@gccr.se', NULL, true, now(), NULL),
  ('ericanorberg85@gmail.com', 'Erica Norberg', true, now(), NULL),
  ('erikssonrydstrom@gmail.com', 'Anna Rydström', true, now(), NULL),
  ('eva.k.hallberg@telia.com', 'Eva Hallberg', true, now(), NULL),
  ('evaulrica37@hotmail.com', 'Ulrica Mattsson', true, now(), NULL),
  ('evis947@gmail.com', NULL, true, now(), NULL),
  ('fontanasabina@hotmail.com', NULL, true, now(), NULL),
  ('gartzy@hotmail.se', 'Gunilla Gartzy', true, now(), NULL),
  ('gillskyllmark@gmail.com', NULL, true, now(), NULL),
  ('gnord51@yahoo.se', NULL, true, now(), NULL),
  ('gunilla.segerson@live.se', NULL, true, now(), NULL),
  ('gunillanornholm@hotmail.com', NULL, true, now(), NULL),
  ('hagg.martinell@icloud.com', NULL, true, now(), NULL),
  ('haidabjo@gmail.com', NULL, true, now(), NULL),
  ('heidi_sandberg@hotmail.com', 'Heidi Sandberg', true, now(), NULL),
  ('hej.carlson@gmail.com', NULL, true, now(), NULL),
  ('hej@petersvardsmyr.se', 'Peter Svärdsmyr', true, now(), NULL),
  ('helenasollenberg@gmail.com', 'Helena Sollenberg', true, now(), NULL),
  ('heleneakesson@icloud.com', 'Helene Åkesson', true, now(), NULL),
  ('hindorf@live.se', NULL, true, now(), NULL),
  ('info@kyrkjobb.se', NULL, true, now(), NULL),
  ('ingela.lundskog@gmail.com', 'Ingela Lundskog', true, now(), NULL),
  ('ingemartinsson1@gmail.com', 'Inge Martinsson', true, now(), NULL),
  ('ingersro@icloud.com', NULL, true, now(), NULL),
  ('jensenslisa@gmail.com', NULL, true, now(), NULL),
  ('johannastorli@gmail.com', 'Johanna Storli', true, now(), NULL),
  ('jonas.konstenius@gmail.com', NULL, true, now(), NULL),
  ('karin_g75@hotmail.com', 'Karin Gunnarsson', true, now(), NULL),
  ('karinhilmer22@gmail.com', 'K***n H****r', true, now(), NULL),
  ('knitter.kmp@gmail.com', 'Km Moritz', true, now(), NULL),
  ('krisah58@gmail.com', 'Kristina Sahlman', true, now(), NULL),
  ('kristinaoscarsson@hotmail.com', 'Kristina Oscarsson', true, now(), NULL),
  ('lavesson33@gmail.com', 'Irene Lavesson', true, now(), NULL),
  ('lena.agestedt@gmail.com', 'Lena Ågestedt', true, now(), NULL),
  ('lena.birath@gmail.com', NULL, true, now(), NULL),
  ('linda_grundstrom@outlook.com', NULL, true, now(), NULL),
  ('lindatheres80@gmail.com', NULL, true, now(), NULL),
  ('lisafridlund@yahoo.se', 'Lisa Fridlund', true, now(), NULL),
  ('lisahager21@hotmail.com', NULL, true, now(), NULL),
  ('lisenaberg@outlook.com', NULL, true, now(), NULL),
  ('lisse78@gmail.com', 'Lisette Lejon', true, now(), NULL),
  ('lottarynbackandersson@gmail.com', 'Lotta Rynbäck Andersson', true, now(), NULL),
  ('lotten@flowernecklace.se', NULL, true, now(), NULL),
  ('lund_anki@hotmail.com', NULL, true, now(), NULL),
  ('lycketorp@gmail.com', 'Marie Hagbom', true, now(), NULL),
  ('m.molldur@gmail.com', NULL, true, now(), NULL),
  ('madelene.svensson74@gmail.com', 'Madelene Svensson', true, now(), NULL),
  ('madelene.vargtass@gmail.com', NULL, true, now(), NULL),
  ('magganbjorkholmen@hotmail.com', NULL, true, now(), NULL),
  ('magnus.nordahl@hotmail.se', NULL, true, now(), NULL),
  ('malin.karlsson@jarfalla.se', NULL, true, now(), NULL),
  ('malin.s.alexandersson@gmail.com', 'Malin Alexandersson', true, now(), NULL),
  ('malinsamson@gmail.com', 'Malin Samson', true, now(), NULL),
  ('marhed14@gmail.com', 'Maria Hedström', true, now(), NULL),
  ('maria-therese.davidsson@svenskakyrkan.se', NULL, true, now(), NULL),
  ('maria.bartens@hotmail.com', NULL, true, now(), NULL),
  ('maria.nilsson9@svenskakyrkan.se', NULL, true, now(), NULL),
  ('maria670820@gmail.com', 'Maria Nilsson', true, now(), NULL),
  ('mariaejenfors@gmail.com', 'Maria Ejenfors', true, now(), NULL),
  ('marica.bergdahl@gmail.com', NULL, true, now(), NULL),
  ('marija.lak@outlook.com', 'Marija Lakotic', true, now(), NULL),
  ('marithebratt@hotmail.com', NULL, true, now(), NULL),
  ('mforsman28@gmail.com', 'Margareta Forsman', true, now(), NULL),
  ('mhedblom@hotmail.com', NULL, true, now(), NULL),
  ('myran_888@hotmail.com', NULL, true, now(), NULL),
  ('nalletanten@hotmail.com', 'Anitha Leidefors', true, now(), NULL),
  ('nenne3@gmail.com', 'Jenny Berging', true, now(), NULL),
  ('netta_ja@hotmail.com', NULL, true, now(), NULL),
  ('norrvik.mgr@gmail.com', 'Marie Gärdebro', true, now(), NULL),
  ('ottossonpia@hotmail.com', 'Pia Ottosson', true, now(), NULL),
  ('pedagoglotta@gmail.com', 'Eva-Lotta Martinsson', true, now(), NULL),
  ('per.a.bulow@gmail.com', NULL, true, now(), NULL),
  ('peter.svardsmyr@gmail.com', 'Peter Svärdsmyr', true, now(), NULL),
  ('peter.svardsmyr@svenskakyrkan.se', NULL, true, now(), NULL),
  ('petra.norin@gmail.com', 'Petra Norin', true, now(), NULL),
  ('petra.piepkorn@telia.com', NULL, true, now(), NULL),
  ('pialisawallin@gmail.com', NULL, true, now(), NULL),
  ('piamarie.westerberg@gmail.com', NULL, true, now(), NULL),
  ('piaviking@gmail.com', 'Pia Løkkeberg', true, now(), NULL),
  ('roger.parvin@telia.com', NULL, true, now(), NULL),
  ('sannesbrev@gmail.com', 'Susanne Lindberg', true, now(), NULL),
  ('shantanyblom@hotmail.com', 'Shanta Nyblom', true, now(), NULL),
  ('sofia@tornstigen.se', 'Sofia Ottosson', true, now(), NULL),
  ('stinahansson1969@gmail.com', NULL, true, now(), NULL),
  ('stinasvensson4@hotmail.com', NULL, true, now(), NULL),
  ('susannaengkvist@hotmail.com', 'Susanna Engqvist', true, now(), NULL),
  ('susanne.kallin@svenskakyrkan.se', NULL, true, now(), NULL),
  ('susannekallin79@gmail.com', 'Susanne Kallin', true, now(), NULL),
  ('svedqvist2@gmail.com', 'Elisabeth Svedqvist', true, now(), NULL),
  ('svenssonmaria2009@gmail.com', 'Maria Svensson', true, now(), NULL),
  ('thereserosdahl79@gmail.com', 'Therese Rosdahl', true, now(), NULL),
  ('to.petrah@gmail.com', NULL, true, now(), NULL),
  ('torsten.wettelius@telia.com', NULL, true, now(), NULL),
  ('u.heldestad@gmail.com', 'Ulrika Heldestad', true, now(), NULL),
  ('ulrika.millstal@gmail.com', NULL, true, now(), NULL),
  ('ulrikandland@gmail.com', NULL, true, now(), NULL),
  ('wira03@hotmail.com', 'Camilla Nelson', true, now(), NULL),
  ('ylva_bergilott@hotmail.com', NULL, true, now(), NULL),
  ('ywonne.bjorkman@gmail.com', 'Ywonne Björkman', true, now(), NULL)
ON CONFLICT (email) DO NOTHING;