// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpehwkimphnkjaxqnpjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZWh3a2ltcGhua2pheHFucGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0Njk4NjYsImV4cCI6MjA3MjA0NTg2Nn0.d34IJQbijXfwV2aAFFC8dQQT0ZL4w6Oq6-hWfywAimQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});